### ISSUE TITLE
Invalid DXF attribute "center" for entity LWPOLYLINE

### ISSUE THREAD

**Issue by bandtank** [georgeh1ll/Easy-DXF-Viewer#3]
The following error was encountered when I tried to view a DXF file:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 140, in open_file
    visualize_dxf(file_path)
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 99, in visualize_dxf
    translate_entities(msp)
  File "/Users/.../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 31, in translate_entities
    min_x = min(ent.dxf.start[0] if ent.dxftype() == 'LINE' else ent.dxf.center[0] for ent in entities)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../Repositories/Easy-DXF-Viewer/Easy DXF Viewer.py", line 31, in <genexpr>
    min_x = min(ent.dxf.start[0] if ent.dxftype() == 'LINE' else ent.dxf.center[0] for ent in entities)
                                                                 ^^^^^^^^^^^^^^
  File "/Users/../Repositories/Easy-DXF-Viewer/venv/lib/python3.11/site-packages/ezdxf/entities/dxfns.py", line 130, in __getattr__
    raise const.DXFAttributeError(
ezdxf.lldxf.const.DXFAttributeError: Invalid DXF attribute "center" for entity LWPOLYLINE
```

However, `ezdxf` does not have a problem converting the dxf to png using the following code:
```
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend
from ezdxf.addons.drawing import Frontend, RenderContext
import ezdxf

import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams['lines.linewidth'] = 5  # set the value globally
mpl.rcParams['patch.linewidth'] = 5  # set the value globally
mpl.rcParams['hatch.linewidth'] = 5  # set the value globally
mpl.rcParams['axes.linewidth'] = 5  # set the value globally

def convert_dxf2img(path, save_to, img_format, img_res):
    doc = ezdxf.readfile(path)
    msp = doc.modelspace()
    auditor = doc.audit()

    if len(auditor.errors) != 0:
        return
    else:
        fig = plt.figure()
        ax = fig.add_axes([0, 0, 1, 1])
        ctx = RenderContext(doc)
        ctx.set_current_layout(msp)
        #ctx.current_layout.set_colors(bg='#FFFFFF')

        out = MatplotlibBackend(ax)
        Frontend(ctx, out).draw_layout(msp, finalize=True)

        fig.savefig(save_to, dpi=img_res)
        plt.close(fig)

convert_dxf2img("perimeter.dxf", "perimeter.png", img_format = '.png', img_res = 300)
```

I'm not sure what is wrong, but it seems to be related to the way `ezdxf` is being called.

**Comment by georgeh1ll** [comment]
Hi Bandtank, 

What dxf file was you using to get this error, I cannot seem to replicate it.

**Comment by bandtank** [comment]
[files.zip](https://github.com/georgeh1ll/Easy-DXF-Viewer/files/13189253/files.zip)

**Comment by georgeh1ll** [comment]
Hi, 

The updated python code can now handle polylines better. 

The perimeter.dxf can now be seen: 
![Screenshot 2023-10-27 142601](https://github.com/georgeh1ll/Easy-DXF-Viewer/assets/11806169/165cbca1-03ba-4fcc-a12c-a9ed2a11c813)

I cannot understand why the elevations file is not working, is it a 3D dxf?

**Comment by bandtank** [comment]
The points have z values, but I wouldn't necessarily call it a 3D file. The `ezdxf` CAD viewer example opens the file, for example, and it only supports 2D files as well. The error for both files is the same regarding the `center` attribute.

**Comment by georgeh1ll** [comment]
Hi, 

The dxf for elevations is not really suited for the type of program I am trying to create. This is meant to be a simple 2D dxf viewer. Changing it to 3D would take a fair bit of rework and is not something I plan on doing. Thanks.
